### PR TITLE
Github Actions workflow

### PR DESCRIPTION
**Pull request by ar-jan**
More or less a port of the .travis.yml contents, may have to be adapted further (#25).

- [x] ~~Modify backend installation to allow using a PostgreSQL connection string with TCP port and password~~
      Providing PostgreSQL environment variables with TCP port is sufficient
- [ ] Handling for Firefox and Chrome?
- [ ] Cache directory declarations?
- [ ] Divide frontend, backend, and functional tests in three steps?

### CODE REVIEW

**Comment by ar-jan** [comment]
~~Looks like we can also use a predefined [Xvfb Action from the marketplace](https://github.com/marketplace/actions/gabrielbb-xvfb-action) for running the headless test.~~

Prefer not to add further dependencies, and looks like it shouldn´t be needed for this.

**Comment by ar-jan** [comment]
Test fails, perhaps because it keeps using Chrome rather than ChromeHeadless?

> Launching browsers Chrome with concurrency unlimited
> Starting browser Chrome
> Cannot start Chrome
> ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
> ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)

On IAnalyzer the log for this step reads `Launching browsers **ChromeHeadless** with concurrency unlimited`.

I've matched the configuration for karma.conf.js with that in IAnalyzer (and als tried adding the  `--disable-gpu` and `--no-sandbox`  flags which were used on Travis and are often mentioned as needed for running headless Chrome), but the test still tries to start Chrome. I've also tried `base: 'ChromeHeadless'` instead of `Chrome` in the customLauncher, same result.

Any ideas, @oktaal @jgonggrijp?

**Comment by jgonggrijp** [comment]
Not really, unfortunately. Haven't seen this problem before. Maybe @oktaal has? Otherwise, either of us could probably study this a little bit next week.

**Comment by ar-jan** [comment]
> Otherwise, either of us could probably study this a little bit next week.

That would be great!

**Comment by jgonggrijp** [comment]
I forgot about this, sorry about that. Fortunately, it looks like @oktaal is working on it.

**Comment by oktaal** [comment]
`karma.conf.js` was in the wrong location. Now it works!

**Comment by ar-jan** [comment]
Great!

Ready to merge?

**Comment by oktaal** [comment]
> * Handling for Firefox and Chrome?
> * [ ]  Cache directory declarations?
> * [ ]  Divide frontend, backend, and functional tests in three steps?

Sure! Might need to move these things to separate issues then.

**Comment by ar-jan** [comment]
Merged. Opened followups #29 and #30. I left out cache dirs (was based on Travis), I suppose we'll find out if/when we need that.

**Comment by jgonggrijp** [comment]
You never really "need" cache dirs. They are a way to save CPU cycles, hence CO2 emissions.

**Pull request merged**
